### ISSUE TITLE
Regarding Position Encoding

### ISSUE THREAD

**Issue by isCopyman** [yandex-research/rtdl-revisiting-models#50]
May I ask if positional encoding of features is important in these Transformer based architectures? It seems that the vast majority of papers do not mention positional encoding. I haven't conducted any relevant experiments, so I'm curious about the results.

**Comment by Yura52** [comment]
Hi! I think the positional encodings are usually not mentioned because there is no explicit sequential structure in tabular data. However, being order-invariant by nature, Transformer has to be aware of each feature position to make reasonable predictions. This is usually achieved with feature embeddings: such modules usually contain parameters that are not shared between features, and as such implicitly contain some information about the feature position.

In particular, in the case of FT-Transformer, non-shared [biases](https://github.com/yandex-research/rtdl-revisiting-models/blob/2542a25b2adbfd0e9d18ce00f75f9f64ad2c26bd/package/rtdl_revisiting_models.py#L193) are especially important despite the presense of non-shared [weights](https://github.com/yandex-research/rtdl-revisiting-models/blob/2542a25b2adbfd0e9d18ce00f75f9f64ad2c26bd/package/rtdl_revisiting_models.py#L193), which is ablated in Section 5.2 of [the paper](https://arxiv.org/pdf/2106.11959).

My informal intuition is that these biases are similar to position encodings. After typical normalizations, the average value of each continuous feature is zero, so the average feature embedding after applying `weights` will also be a zero vector, so Transformer will no able to distinguish one feature from another. Biases fix this issue.

**Comment by isCopyman** [comment]
Thank you for your answer. Indeed, different embedding matrices combined with bias are somewhat similar to positional encoding, which is equivalent to a learnable positional encoding.
